---
name: Lint and Build
on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'bugfix/**'
      - 'releases/**'

  pull_request:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: "1.22"

      - name: Run hadolint
        uses: reviewdog/action-hadolint@v1
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:    
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.x'

      - name: Install dependencies
        run: go get .

      - name: Test
        run: go test -v ./... --race

      - name: Build
        run: go build -v ./...
      - name: Build an image from Dockerfile
        run: |
          docker build -t controlplane/netassertv2-l4-client:${{ github.sha }} .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'controlplane/netassertv2-l4-client:${{ github.sha }}'
          format: 'table'
          ignore-unfixed: true
          exit-code: '1'
          vuln-type: 'os,library'
          output: 'trivy-results.txt'
          severity: 'CRITICAL,HIGH,MEDIUM'
      - run: cat trivy-results.txt
